config/routes.rb
Rails.application.routes.draw do
  get 'send/contact'

  root 'pages#home'
  get 'about' =>'pages#nosotros'
  get 'catalogo' => 'portfolio#portafolio'
  get 'servicios' => 'services#servicios'
  get 'clientes' => 'clients#clientes'

  get 'send' => 'send#contact'
  post 'send' => 'send#create'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	def clientes
		
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home	
	end

	def about	
	end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
	def catalogo
		
	end
end

app/controllers/send_controller.rb
class SendController < ApplicationController
  def contact
  end

def create 
 @params= params
 ContactMailer.contact_send(params).deliver_now 
 flash[:notice]= "mensaje enviado"
 redirect_to send_path
end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
	def servicios
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/send_helper.rb
module SendHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/clients/clientes.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon-02.png">

      <title>COCIT</title>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
	<script src="https://use.fontawesome.com/e8ebcfe0ff.js"></script>
	<link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=PT+Mono" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Aldrich|Carrois+Gothic+SC|Finger+Paint|Rajdhani|Ubuntu+Condensed" rel="stylesheet">

</head>

  <body>
      <div class="cuarto" data-parallax="scroll" data-image-src="img/puntos-naranja-07.svg">
        <div class="titulo5" >
          <p style="font-size: 50pt; color: #FFB131;">ELLOS CONFIAN EN NOSOTROS:</p>
        </div>
        <div class="container">
        <div class="row clientes">
            <div class="col-sm-4">     
                <img class="img-responsive img-center hvr-pulse-grow" src="img/porcelanite-08.svg" style="width:450px" alt="Porcelanite">
            </div>
            <div class="col-sm-4">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/Flowserve.png" style="width:250px" alt="FLOWSERVE">
            </div> 
            <div class="col-sm-4">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/kimberly-09.svg" style="width:450px" alt="Kimberly">
            </div> 
        </div>
        <div class="row clientes2">
            <div class="col-sm-4">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/BUAP2.png" style="height:150px; width:150px" alt="BUAP">
            </div>
            <div class="col-sm-4">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/femsa.png" style="width:250px" alt="FEMSA">
            </div>
            <div class="col-sm-4">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/nissan-01.png" style="height:150px; width:150px" alt="Nissan">
            </div>
        </div>
        <div class="row clientes2">
            <div class="col-sm-4">     
                <img class="img-responsive img-center hvr-pulse-grow" src="img/vesta.jpg" style="height:130px; width:300px" alt="Vesta">
            </div>
            <div class="col-sm-4">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/cydsa-logo2.jpg" style="height:130px; width:300px" alt="Cydsa">
            </div>
            <div class="col-sm-4">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/greenbrier-13.svg" style="width:230px" alt="Greenbrier">
            </div>
        </div>
        <div class="row clientes2">
            <div class="col-sm-3">     
                <img class="img-responsive img-center hvr-pulse-grow" src="img/Logo_Vetrotex.jpg" style="height:130px; width:400px" alt="Vetrotex">
            </div>
            <div class="col-sm-3">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/polaquimia-12.svg" alt="Polaquimia">
            </div>
            <div class="col-sm-3">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/saint-gobain-11.svg" alt="Saint-Gobain">
            </div>
            <div class="col-sm-3">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/simec.png" style="height:70px;" alt="Simec">
            </div>
        </div>
        </div>
          
        </div>

      <footer>
        <p>&copy; 2017 COCIT S.A de C.V. &middot;</a></p>
      </footer>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>COCIT</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body style="overflow-x: hidden;">

<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="height:77px; padding:0px; background-color:#FFFFFF;">
        <div style="padding:0px; margin:0px 30px 0px 0px;">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header" style="padding:0px 40px 0px 0px;">
               <img class="logo" src="img/logocorto-02.svg"  style="width:25em; height:7em;" align="left"></a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hvr-underline-from-center">
                        <a style="padding:10px;"><%= link_to "COCIT", root_path%></a>
                    </li>
                    <li class="hvr-underline-from-center">
                        <a style="padding:10px"><%= link_to "NOSOTROS", about_path%></a>
                    </li>
                    <li class="hvr-underline-from-center">
                        <a style="padding:10px"><%= link_to "PORTAFOLIO", catalogo_path%></a>
                    </li>
                    <li class="hvr-underline-from-center">
                        <a style="padding:10px"><%= link_to "SERVICIOS", servicios_path%></a>
                    </li>
                    <li class="hvr-underline-from-center">
                        <a style="padding:10px"><%= link_to "CLIENTES", clientes_path %></a>
                    </li>
                    <li class="hvr-underline-from-center">
                        <a style="padding:10px"><%= link_to "CONTACTO", send_path%></a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <%= favicon_link_tag 'favicon.ico' %>
      
      <title>COCIT</title>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
	<script src="https://use.fontawesome.com/e8ebcfe0ff.js"></script>
	<link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=PT+Mono" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Aldrich|Carrois+Gothic+SC|Finger+Paint|Rajdhani|Ubuntu+Condensed" rel="stylesheet">



  </head>

  <body>
                
    <!-- Carousel
    ================================================== -->
        <!-- Wrapper for Slides -->
        <div class="carousel-inner carousel primera" id="myCarousel" data-ride="carousel" style="width: 100%; height:100%; margin-top:75px;">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
      </ol>
            <div class="item active" id="myCarousel">
                <!-- Set the first background image using inline CSS below. -->
                <div class="fill" id="myCarousel" style="background-image:url('img/principal-03.jpg');">
                  <p class="banners3"> En COCIT tenemos la capacidad técnica necesaria <br> para el desarrollo de sus proyectos.</p>
                </div>              
            </div>
            <div class="item">
                <!-- Set the second background image using inline CSS below. -->
                <div class="fill" id="myCarousel" style="background-image:url('img/principal-05.jpg');">
                  <p class="banners3"> En COCIT tenemos la capacidad técnica necesaria <br> para el desarrollo de sus proyectos.</p>
                </div>
            </div>
            <div class="item">
                <!-- Set the third background image using inline CSS below. -->
                <div class="fill" id="myCarousel" style="background-image:url('img/principal-04.jpg');">
                  <p class="banners3"> En COCIT tenemos la capacidad técnica necesaria <br> para el desarrollo de sus proyectos.</p>
                </div>
            </div>
             <div class="item">
                <!-- Set the third background image using inline CSS below. -->
                <div class="fill" id="myCarousel" style="background-image:url('img/home2-09-09.jpg');">
                  <p class="banners3"> En COCIT tenemos la capacidad técnica necesaria <br> para el desarrollo de sus proyectos.</p>
                </div>
            </div>
             <div class="item">
                <!-- Set the third background image using inline CSS below. -->
                <div class="fill" id="myCarousel" style="background-image:url('img/home-09.jpg');">
                  <p class="banners3"> En COCIT tenemos la capacidad técnica necesaria <br> para el desarrollo de sus proyectos.</p>
                </div>
            </div>
        </div>
<!--
        <a class="carousel-control left" href="#myCarousel"  data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="carousel-control right" href="#myCarousel"  data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
-->     

    <!-- CIRCLES
    ================================================== -->
    <div class="segunda" data-parallax="scroll" data-image-src="img/puntos-01.png"> 
        <div class="titulo3" >
           <a href="about" style="font-size: 70pt; color: #FFB131; text-decoration:none;">NOSOTROS</a> 
        </div> 
    	<div class="row">
            <div class="col-sm-4"> 
              <a href="about"> 
                <img class="img-responsive img-center hvr-pulse-grow" src="img/mision-03.png" alt="Misión">
              </a> 
                <h2>MISIÓN</h2>
            </div>
            <div class="col-sm-4">
              <a href="about">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/vision-04.png" alt="Visión">
              </a>
                <h2>VISIÓN</h2>
            </div>
            <div class="col-sm-4">
              <a href="about">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/politicas-05.png" alt="Política de Calidad">
              </a>
                <h2>POLÍTICA <br> DE CALIDAD</h2>
            </div>
        </div>
    </div>

      <!-- START THE FEATURETTES -->
      <div class="tercero" data-parallax="scroll" data-image-src="" >
        <div class="titulo3" >
           <a href="servicios" style="font-size: 70pt; color: #FFB131; text-decoration:none;">SERVICIOS</a> 
        </div>
        <div class="row">
            <div class="col-sm-3 nopadding imghvr-zoom-out">
              <a href="servicios"></a> 
                <img class="cuadro img-responsive" src="img/acabados.jpg">
                  <figcaption style="background-color:#FFB131; text-align:center; padding-top:100px;">
                    <h2 class="sub">ACABADOS EPOXICOS</h2>
                  </figcaption>
            </div>
            <div class="col-sm-3 nopadding imghvr-blur">
              <a href="servicios"></a>  
                <img class="cuadro img-responsive" src="img/cimentacion.jpg">
                  <figcaption style="background-color:#BDBEC0; text-align:center; padding-top:100px;">
                    <h2 class="sub">CIMENTACIONES</h2>
                  </figcaption>
            </div>
            <div class="col-sm-3 nopadding imghvr-zoom-out" >
              <a href="servicios"></a>  
                <img class="cuadro img-responsive" src="img/edificios.jpg">
                  <figcaption style="background-color:#FFB131; text-align:center; padding-top:100px;">
                    <h2 class="sub">EDIFICIOS</h2>
                  </figcaption>
            </div>
            <div class="col-sm-3 nopadding imghvr-blur" >
              <a href="servicios"></a> 
                <img class="cuadro img-responsive" src="img/estructurametal.jpg">
                  <figcaption style="background-color:#BDBEC0; text-align:center; padding-top:100px;">
                    <h2 class="sub">ESTRUCTURA METALICA Y LAMINACIÓN</h2>
                  </figcaption>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3 nopadding imghvr-blur">
              <a href="servicios"></a>       
                <img class="cuadro img-responsive" src="img/impermeBuap.jpg">
                  <figcaption style="background-color:#BDBEC0; text-align:center; padding-top:100px;">
                    <h2 class="sub">IMPERMEABILIZACIÓN</h2>
                  </figcaption>
            </div>
            <div class="col-sm-3 nopadding imghvr-zoom-out">
              <a href="servicios"></a> 
                <img class="cuadro img-responsive" src="img/concretoflowserve.jpg">
                  <figcaption style="background-color:#FFB131; text-align:center; padding-top:100px;">
                    <h2 class="sub">PISOS DE CONCRETO Y ASFALTO</h2>
                  </figcaption>
            </div>
            <div class="col-sm-3 nopadding imghvr-blur" >
              <a href="servicios"></a> 
                <img class="cuadro img-responsive" src="img/restauracion2.jpg">
                  <figcaption style="background-color:#BDBEC0; text-align:center; padding-top:100px;">
                    <h2 class="sub">REMODELACIÓN Y RESTAURACIÓN</h2>
                  </figcaption>
            </div>
            <div class="col-sm-3 nopadding imghvr-zoom-out">
              <a href="servicios"></a>  
                <img class="cuadro img-responsive" src="img/tuberias.jpg">
                  <figcaption style="background-color:#FFB131; text-align:center; padding-top:100px;">
                    <h2 class="sub">TUBERIAS Y DRENAJES</h2>
                  </figcaption>
            </div>
        </div>
      </div>


      <div class="cuarto" data-parallax="scroll" data-image-src="img/puntos-naranja-07.svg">
        <div class="titulo3" >
          <a href="clientes" style="font-size: 70pt; color: #FFB131; text-decoration:none;">CLIENTES</a>
        </div>
        <div class="container">
        <div class="row clientes">
            <div class="col-sm-4">     
                <img class="img-responsive img-center hvr-pulse-grow" src="img/porcelanite-08.svg" style="width:450px" alt="Porcelanite">
            </div>
            <div class="col-sm-4">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/Flowserve.png" style="width:250px" alt="FLOWSERVE">
            </div> 
            <div class="col-sm-4">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/kimberly-09.svg" style="width:450px" alt="Kimberly">
            </div> 
        </div>
        <div class="row clientes2">
            <div class="col-sm-4">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/BUAP2.png" style="height:150px; width:150px" alt="BUAP">
            </div>
            <div class="col-sm-4">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/femsa.png" style="width:250px" alt="FEMSA">
            </div>
            <div class="col-sm-4">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/nissan-01.png" style="height:150px; width:150px" alt="Nissan">
            </div>
        </div>
        <div class="row clientes2">
            <div class="col-sm-4">     
                <img class="img-responsive img-center hvr-pulse-grow" src="img/vesta.jpg" style="height:130px; width:300px" alt="Vesta">
            </div>
            <div class="col-sm-4">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/cydsa-logo2.jpg" style="height:130px; width:300px" alt="Cydsa">
            </div>
            <div class="col-sm-4">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/greenbrier-13.svg" style="width:230px" alt="Greenbrier">
            </div>
        </div>
        <div class="row clientes2">
            <div class="col-sm-3">     
                <img class="img-responsive img-center hvr-pulse-grow" src="img/Logo_Vetrotex.jpg" style="height:130px; width:400px" alt="Vetrotex">
            </div>
            <div class="col-sm-3">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/polaquimia-12.svg" alt="Polaquimia">
            </div>
            <div class="col-sm-3">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/saint-gobain-11.svg" alt="Saint-Gobain">
            </div>
            <div class="col-sm-3">
                <img class="img-responsive img-center hvr-pulse-grow" src="img/simec.png" style="height:70px;" alt="Simec">
            </div>
        </div>
        </div>
          
        </div>

      <!-- /END THE FEATURETTES -->
    <script>
    $('.carousel').carousel({
        interval: 2000 //changes the speed
    })
    </script>

      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Volver arriba</a></p>
        <p>&copy; 2017 COCIT S.A de C.V. &middot;</a></p>
      </footer>

    </div><!-- /.container -->
  </body>
</html>

app/views/pages/nosotros.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>COCIT</title>

<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
    <script src="https://use.fontawesome.com/e8ebcfe0ff.js"></script>
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=PT+Mono" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Aldrich|Carrois+Gothic+SC|Finger+Paint|Rajdhani|Ubuntu+Condensed" rel="stylesheet">
</head>
<body>

        <div class="primera" data-parallax="scroll">
            <div class="container1">
              <p class="banners flex">NOSOTROS</p>
              <p class="banners2 flex"> En COCIT tenemos la capacidad técnica necesaria <br> para el desarrollo de sus proyectos.</p>
            </div>
          <img src="img/nosotros.jpg" style="width:100%; height:100%" >
        </div>

 <div class="container" style="margin-top:50px;">
        <!-- Project One -->
        <div class="row">
            <div class="col-md-8">
            	<div class="titulo2">
                <p style="font-size: 50pt;">MISIÓN</p>
                </div>
                <p class="parrafos"> 
                    SOMOS UN GRUPO DE INGENIEROS Y ARQUITECTOS MEXICANOS, QUIENES ESTAMOS COMPROMETIDOS CON EL SECTOR PÚBLICO Y PRIVADO A DESARROLLAR OBRAS DE CALIDAD, ESTANDO A LA VANGUARDIA DE NUEVOS PROCESOS CONSTRUCTIVOS Y LA CONSTANTE CAPACITACIÓN DE NUESTRO PERSONAL, TODOS LOS QUE FORMAMOS PARTE DE ESTE GRUPO ESTAMOS CONVENCIDOS QUE PARA LOGRAR LA SATISFACCIÓN TOTAL DE NUESTROS CLIENTES DEBEMOS CUMPLIR CON LOS TIEMPOS PACTADOS PARA LA EJECUCIÓN DE LA OBRA, SIN PONER EN RIESGO LA SEGURIDAD DE PERSONAL INVOLUCRADO DIRECTA O INDIRECTAMENTE, CUIDANDO LA CALIDAD, COSTOS Y RESPETANDO SIEMPRE AL MEDIO AMBIENTE.
                </p>
            </div>
            <div class="col-md-4">
                <a href="#">
                    <img class="img-responsive img-center" src="img/mision-03.png" alt="Misión">
                </a>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Project Two -->
        <div class="row">
            <div class="col-md-4">
                <a href="#">
                    <img class="img-responsive img-center size" src="img/vision-04.png" alt="Misión">
                </a>
            </div>
            <div class="col-md-8">
            	<div class="titulo2">
                <p style="font-size: 50pt;">VISIÓN</p>
                </div>
                <p class="parrafos"> 
                    EN PRIMER PLANO CONSOLIDARNOS Y SER PROTAGONISTAS DENTRO DEL ESTADO COMO UNO DE LOS MEJORES GRUPOS DEDICADOS A LA INDUSTRIA DE LA CONSTRUCCIÓN, FORMANDO UN EQUIPO COMPETITIVO, EFICIENTE, CONFIABLE, EFICAZ Y RENTABLE, RECONOCIDOS SIEMPRE POR LA HONESTIDAD Y PROFESINALISMO DE CADA UNO DE LOS INTEGRANTES QUE FORMAN PARTE DE ESTE GRUPO. Y ESTO NOS SIRVA PARA SER CONSIDERADOS EN ALGÚN MOMENTO EN EL RESTO DEL PAÍS.
                </p>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Project Three -->
        <div class="row">
            <div class="col-md-8">
            	<div class="titulo2">
                <p style="font-size: 50pt;">POLÍTICA DE CALIDAD</p>
                </div> 
                <p class="parrafos"> EN GRUPO CONSTRUCTOR COCIT TENEMOS COMO PRIORIDAD LA TOTAL SATISFACCIÓN DE NUESTROS CLIENTES DE UNA MANERA PROFESIONAL Y APEGADA A ESTANDARES DE CALIDAD ASÍ COMO LA CONTINUA CAPACITACIÓN DE NUESTRO RECURSO HUMANO 
                </p>
            </div>
            <div class="col-md-4">
                <a href="#">
                    <img class="img-responsive img-center" src="img/politicas-05.png" alt="Misión">
                </a>
            </div>
        </div>
        <!-- /.row -->
 </div>

       <footer>
        <p>&copy; 2017 COCIT S.A de C.V. &middot;</a></p>
      </footer>
        
</body>
</html>